# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  # Load Balancer + Consul Server
  config.vm.define :lb do |lb|
    lb.vm.network :private_network, ip: "192.168.100.2"
    lb.vm.hostname = "haproxy-lb"
    lb.vm.provision "shell", path: "provision_lb.sh"
  end

  # Web Server 1 + Consul Client
  config.vm.define :web1 do |web1|
    web1.vm.network :private_network, ip: "192.168.100.3"
    web1.vm.hostname = "web1"
    web1.vm.provision "shell", path: "provision_web.sh", args: ["192.168.100.3"]
  end

  # Web Server 2 + Consul Client
  config.vm.define :web2 do |web2|
    web2.vm.network :private_network, ip: "192.168.100.4"
    web2.vm.hostname = "web2"
    web2.vm.provision "shell", path: "provision_web.sh", args: ["192.168.100.4"]
    web2.vm.boot_timeout = 1000
  end
end