apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-excalidraw
spec:
  replicas: 2
  selector:
    matchLabels:
      app: excalidraw
  template:
    metadata:
      labels:
        app: excalidraw
    spec:
      containers:
      - name: excalidraw
        image: excalidraw/excalidraw:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: excalidraw-service
spec:
  type: LoadBalancer
  selector:
    app: excalidraw
  ports:
  - port: 80
    targetPort: 80